### ISSUE TITLE
Test run fails on PRs from forks due to missing secrets

### ISSUE THREAD

**Issue by Fayti1703** [comcode-org/hackmud_wiki#492]
### Problem

The test runs on pull requests from forked repositories (e.g. #491) fail because of missing Algoila app secrets. These secrets aren't provided due to a GitHub security feature. ([see note in docs](https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow))

This prevents merging pull requests from non-volunteers.

### Context

Might need to make the Algoila search optional (and remove the integration when missing secrets)

**Comment by seanmakesgames** [comment]
That sounds like a good plan (turning algolia off when secrets not available)

**Comment by seanmakesgames** [comment]
blocks all community PRs from merge

**Comment by matr1x-hackmud** [comment]
This issue is still happening on community PRs:

https://github.com/comcode-org/hackmud_wiki/actions/runs/12151245807/job/33885502732?pr=495
```
Error: Unable to build website for locale en.
    at tryToBuildLocale (/home/runner/work/hackmud_wiki/hackmud_wiki/node_modules/.pnpm/@docusaurus+core@3.0.1_@docusaurus+types@3.0.1_react-dom@18.3.1_react@18.2.0__react@18.2.0__r_l3lzq6i465gal5belpvl4yvf2a/node_modules/@docusaurus/core/lib/commands/build.js:55:19)
    at async mapAsyncSequential (/home/runner/work/hackmud_wiki/hackmud_wiki/node_modules/.pnpm/@docusaurus+utils@3.0.1_@docusaurus+types@3.0.1_react-dom@18.3.1_react@18.2.0__react@18.2.0_/node_modules/@docusaurus/utils/lib/jsUtils.js:44:24)
    at async Command.build (/home/runner/work/hackmud_wiki/hackmud_wiki/node_modules/.pnpm/@docusaurus+core@3.0.1_@docusaurus+types@3.0.1_react-dom@18.3.1_react@18.2.0__react@18.2.0__r_l3lzq6i465gal5belpvl4yvf2a/node_modules/@docusaurus/core/lib/commands/build.js:82:21) {
  [cause]: [Error [ValidationError]: "algolia.appId" is not allowed to be empty] {
    _original: {
      colorMode: [Object],
      docs: [Object],
      navbar: [Object],
      footer: [Object],
      algolia: [Object],
      metadata: [],
      prism: [Object],
      tableOfContents: [Object]
    },
    details: [ [Object] ]
  }
}
```
